### ISSUE TITLE
Readme clarification: required boolector version

### ISSUE THREAD

**Issue by daxtens** [uw-unsat/serval-bpf#1]
Hi - thanks for presenting this at LPC2020. I'm looking at possible applications for ppc64.

I found that the version of boolector supplied with Ubuntu 20.04 doesn't work with your code. (I eventually figured this out by looking at your CI scripts, thanks for supplying those.) I think it's because Ubuntu ships an extremely ancient version of boolector - version 1.5! Things seem to be working with the Ubuntu-supplied z3 (version 4.8.7) and racket (version 7.2). 

Would you consider adding a note to the README about the versions of boolector you require/have tested against?

**Comment by lukenels** [comment]
Thanks!

I just pushed a change to README specifying that we test with Boolector v3.2.1.
We don't aim to support older versions of Racket, but if 7.2 works for you then I don't know of any specific reason you would need to upgrade.
